### ISSUE TITLE
Ignore local files

### ISSUE THREAD

**Issue by MaluNoPeleke** [xyc/vscode-mdx-preview#11]
It seems to be a VS Code constraint to not render local files which is annoying in a case such as 

`<img src={require('src/img/enews.png')} />`
![image](https://user-images.githubusercontent.com/1446541/58189474-db81f800-7cba-11e9-809b-594c0466674d.png)

For such cases could a static placeholder just display something and still render the rest of the mdx instead of failing to compile?

**Comment by xyc** [comment]
This should be supported actually. Would you like to try `require('./src/img/enews.png')`?
