### ISSUE TITLE
Use of MDX Image fails

### ISSUE THREAD

**Issue by qmatto** [xyc/vscode-mdx-preview#12]
Using the following MDX file fails in the preview:

```
import { the\mes } from 'mdx-deck'
import { Image } from 'mdx-deck';

export const theme = themes.condensed

<Image src='kittens.png'>

# Kittens

</Image>

With error:
```

> Unhandled Rejection (Error): React is not defined

Any help would be much appreciated

**Comment by xyc** [comment]
Looks that `Image` (https://github.com/jxnblk/mdx-deck/blob/master/packages/gatsby-theme/src/components/image.js#L1) uses custom jsx pragma https://github.com/system-ui/theme-ui#sx-prop

Custom jsx pragma is not supported at the moment. Need more thoughts into how this could be supported.
