### ISSUE TITLE
External React component causes an error

### ISSUE THREAD

**Issue by keita-makino** [xyc/vscode-mdx-preview#13]
I have the following mdx and tsx.

```
// mdx
import Test from '../components/Test.tsx';

# hoge

<Test />

// tsx
import React from 'react';
import { Grid } from '@material-ui/core';

const Test: React.FC = () => {
  return <Grid>hoge</Grid>;
};

export default Test;
```

but it will cause an error `Cannot find module 'npm://./Zoom'` in the preview.

Aren't external components supported?

**Comment by xyc** [comment]
Will take a look this weekend. Do you mind making a codesandbox repro?

**Comment by keita-makino** [comment]
@xyc I made a repository for this issue.

1. Clone the repo
2. Install "mdx" and "mdx-preview" vscode extensions.
3. npm start
4. Confirm that the mdx is shown in the browser.
5. Confirm that the mdx preview in the extension does not work with the error "Cannot find module 'npm://./Zoom'"

**Comment by xyc** [comment]
Thanks for making the repro, but I can't repro this issue.

<img width="1068" alt="Screen Shot 2019-09-13 at 10 38 09 PM" src="https://user-images.githubusercontent.com/679275/64903981-5494c900-d677-11e9-80dd-ff65b839ef5a.png">

Are you previewing `document.mdx` file?

**Comment by keita-makino** [comment]
Yes indeed. This is what I see in my vscode.

![image](https://user-images.githubusercontent.com/42898720/64983620-c9355680-d875-11e9-9be4-da0ef68c759b.png)

**Comment by xyc** [comment]
@keita-makino Looks that you are on Windows? It seems that the path `./Zoom` need to be normalized (to be converted to forward slash on Windows). I'll try to repro this

**Comment by keita-makino** [comment]
@xyc Yes I'm on Windows. Let me know if you could repro this :)

**Comment by xyc** [comment]
@keita-makino Yes, I can indeed repro this on windows :) Thanks for reporting this! The cause is that the npm packages installed still have forward slash `/` when installed on windows. I'll work on a fix this weekend.

**Comment by xyc** [comment]
@keita-makino update to `0.2.2` & try it :) let me know if you still have an issue. Thanks again for reporting this

**Comment by keita-makino** [comment]
@xyc It worked! Thank you for your assistance and improvement :)

**Comment by xyc** [comment]
@keita-makino you are welcome!
