### ISSUE TITLE
Changes on imported components not live reloading

### ISSUE THREAD

**Issue by edmo0031** [xyc/vscode-mdx-preview#21]
My folder structure is as follows:

```
root
|_ docs
   |_ foo.mdx
   |_ components
      |_ Bar.jsx
```

In `foo.mdx` is the following:

```js
import { Bar } from './components/Bar.jsx';
```

When I make changes to `Bar.jsx`, it is not reflected in the preview for `Foo.mdx`, until I close and reopen `Foo.mdx`, or hit the refresh button on the preview window.

I'm using 0.2.2 of the plugin.

**Comment by xyc** [comment]
Can you create a codesandbox repro of this issue if it's still reproducible? Feel free to reopen this issue if it still persists.
