### ISSUE TITLE
Feature request: update preview when referenced component changes

### ISSUE THREAD

**Issue by allforabit** [xyc/vscode-mdx-preview#5]
Currently the preview only seems to update when the actual mdx file is updated. It would be nice however if it updated when the component or components that it references is updated. The use case is to use it as a way to preview components under development and visually see the changes conveniently in the editor alongside the code. 

Thanks for the great extension!

**Comment by xyc** [comment]
Yes that's definitely considered and I'd love to have that as well! I have a working branch that's hopefully get released along with TypeScript support. Thanks!

**Comment by allforabit** [comment]
Great thanks for this. I'll give this branch a test when I get a chance.

**Comment by xyc** [comment]
😊sneak peek! Releasing this soonish
![hot-reload](https://user-images.githubusercontent.com/679275/56944314-c78e1080-6ad7-11e9-8f9b-f305740d3ab4.gif)

**Comment by xyc** [comment]
Released in v0.2.0
