### ISSUE TITLE
#Error Icon# preview icon error in vscode 

### ISSUE THREAD

**Issue by HondryTravis** [xyc/vscode-mdx-preview#51]
can you see that. 
vscode versions: 1.56.0
platform: macos 10.15.x

preview icon error
![image](https://user-images.githubusercontent.com/24218012/117254729-567a5400-ae7b-11eb-83a4-687710f3bbd2.png)

**Comment by xyc** [comment]
@HondryTravis Do you happen to use VS Code insiders version or regular version?
