### ISSUE TITLE
missing code highlight

### ISSUE THREAD

**Issue by naivefun** [xyc/vscode-mdx-preview#9]
The code is just plain color. Is there a way to add highlight.js?

And is there a way to add styles to preview page?

**Comment by xyc** [comment]
You can apply a custom layout: https://github.com/xyc/vscode-mdx-preview#custom-layout
Example Layout component (MDX v0.20): https://github.com/mdx-js/mdx/blob/v0.20.4/examples/syntax-highlighting/src/components/Layout.js

Default VS Code markdown style currently doesn't have highlighting. I'll add it to the roadmap.

**Comment by xyc** [comment]
If you are looking for a way to style the preview page itself, you can just put `import './my-styles.css';` at the top of mdx file.
